INSERT INTO student(name, birthday, groupnumber) VALUES ('John', current_date, 1);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Chris', current_date, 1);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Carl', current_date, 1);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Oliver', current_date, 2);
INSERT INTO student(name, birthday, groupnumber) VALUES ('James', current_date, 2);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Lucas', current_date, 2);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Henry', current_date, 2);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Jacob', current_date, 3);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Logan', current_date, 3);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Ben', current_date, 4);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Mary', current_date, 4);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Fred', current_date, 5);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Ann', current_date, 5);
INSERT INTO subject(name, grade) VALUES ('Art', 1);
INSERT INTO subject(name, grade) VALUES ('Music', 1);
INSERT INTO subject(name, grade) VALUES ('Geography', 2);
INSERT INTO subject(name, grade) VALUES ('History', 2);
INSERT INTO subject(name, grade) VALUES ('PE', 3);
INSERT INTO subject(name, grade) VALUES ('Math', 3);
INSERT INTO subject(name, grade) VALUES ('Science', 4);
INSERT INTO subject(name, grade) VALUES ('IT', 4);
INSERT INTO subject(name, grade) VALUES ('Astronomy', 5);
INSERT INTO subject(name, grade) VALUES ('Physic', 5);
INSERT INTO paymenttype(name) VALUES ('DAILY');
INSERT INTO paymenttype(name) VALUES ('WEEKLY');
INSERT INTO paymenttype(name) VALUES ('MONTHLY');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='WEEKLY', 150, current_timestamp(), SELECT id FROM student WHERE name='John');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='MONTHLY', 450, current_timestamp(), SELECT id FROM student WHERE name='Oliver');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='WEEKLY', 125, current_timestamp(), SELECT id FROM student WHERE name='Henry');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='DAILY', 15, current_timestamp(), SELECT id FROM student WHERE name='James');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='MONTHLY', 425, current_timestamp(), SELECT id FROM student WHERE name='Jacob');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='DAILY', 12, current_timestamp(), SELECT id FROM student WHERE name='Ben');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='WEEKLY', 107, current_timestamp(), SELECT id FROM student WHERE name='Ann');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='MONTHLY', 410, current_timestamp(), SELECT id FROM student WHERE name='Chris');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='MONTHLY', 412, current_timestamp(), SELECT id FROM student WHERE name='Carl');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='DAILY', 19, current_timestamp(), SELECT id FROM student WHERE name='Lucas');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='WEEKLY', 98, current_timestamp(), SELECT id FROM student WHERE name='Logan');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='MONTHLY', 395, current_timestamp(), SELECT id FROM student WHERE name='Mary');
INSERT INTO payment(type_id, amount, payment_date, student_id) VALUES (SELECT id FROM paymenttype WHERE name='DAILY', 18, current_timestamp(), SELECT id FROM student WHERE name='Fred');
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='Chris', SELECT id FROM subject WHERE name='Art', 8);
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='Oliver', SELECT id FROM subject WHERE name='History', 5);
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='James', SELECT id FROM subject WHERE name='Geography', 9);
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='Jacob', SELECT id FROM subject WHERE name='Math', 4);
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='Logan', SELECT id FROM subject WHERE name='PE', 9);
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='John', SELECT id FROM subject WHERE name='Music', 7);
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='Carl', SELECT id FROM subject WHERE name='Art', 6);
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='Lucas', SELECT id FROM subject WHERE name='History', 9);
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='Henry', SELECT id FROM subject WHERE name='Geography', 8);
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='Ben', SELECT id FROM subject WHERE name='IT', 7);
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='Mary', SELECT id FROM subject WHERE name='Science', 8);
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='Fred', SELECT id FROM subject WHERE name='Physic', 5);
INSERT INTO mark(student_id, subject_id, mark) VALUES (SELECT id FROM student WHERE name='Ann', SELECT id FROM subject WHERE name='Astronomy', 9);